"""create tables

Revision ID: 9dd5236bd4f8
Revises: 
Create Date: 2025-07-10 10:27:11.326251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dd5236bd4f8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nombre', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('apellido', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('telefono', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telefono')
    op.drop_column('users', 'apellido')
    op.drop_column('users', 'nombre')
    # ### end Alembic commands ###
